// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUZyMvWT0nv8FgFW8MQNZTNHdVo1ROjQ',
    appId: '1:641515537666:web:2758acc61da6d1c7a0ee1b',
    messagingSenderId: '641515537666',
    projectId: 'order-app-3f867',
    authDomain: 'order-app-3f867.firebaseapp.com',
    storageBucket: 'order-app-3f867.firebasestorage.app',
    measurementId: 'G-DMEBHFKTRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUdJ5DBlIlAv0k4_bJWYnosBwL9w8oKk',
    appId: '1:641515537666:android:c8df1aa06e994b91a0ee1b',
    messagingSenderId: '641515537666',
    projectId: 'order-app-3f867',
    storageBucket: 'order-app-3f867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9OqYLDA1W4f5yyCPVBqsBqrDYxgeKmI',
    appId: '1:641515537666:ios:c5823b7c179e8c32a0ee1b',
    messagingSenderId: '641515537666',
    projectId: 'order-app-3f867',
    storageBucket: 'order-app-3f867.firebasestorage.app',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj9OqYLDA1W4f5yyCPVBqsBqrDYxgeKmI',
    appId: '1:641515537666:ios:c5823b7c179e8c32a0ee1b',
    messagingSenderId: '641515537666',
    projectId: 'order-app-3f867',
    storageBucket: 'order-app-3f867.firebasestorage.app',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIUZyMvWT0nv8FgFW8MQNZTNHdVo1ROjQ',
    appId: '1:641515537666:web:9c6aaf9257fdd1c4a0ee1b',
    messagingSenderId: '641515537666',
    projectId: 'order-app-3f867',
    authDomain: 'order-app-3f867.firebaseapp.com',
    storageBucket: 'order-app-3f867.firebasestorage.app',
    measurementId: 'G-SKM7T33XNS',
  );

}